ALTER TABLE `armor` ADD COLUMN `dropable` VARCHAR(5) DEFAULT 'true' AFTER `sellable`;
ALTER TABLE `etcitem` ADD COLUMN `dropable` VARCHAR(5) DEFAULT 'true' AFTER `sellable`;
ALTER TABLE `weapon` ADD COLUMN `dropable` VARCHAR(5) DEFAULT 'true' AFTER `sellable`;
ALTER TABLE `armor` ADD COLUMN `destroyable` VARCHAR(5) DEFAULT 'true' AFTER `dropable`;
ALTER TABLE `etcitem` ADD COLUMN `destroyable` VARCHAR(5) DEFAULT 'true' AFTER `dropable`;
ALTER TABLE `weapon` ADD COLUMN `destroyable` VARCHAR(5) DEFAULT 'true' AFTER `dropable`;
ALTER TABLE `armor` ADD COLUMN `tradeable` VARCHAR(5) DEFAULT 'true' AFTER `destroyable`;
ALTER TABLE `etcitem` ADD COLUMN `tradeable` VARCHAR(5) DEFAULT 'true' AFTER `destroyable`;
ALTER TABLE `weapon` ADD COLUMN `tradeable` VARCHAR(5) DEFAULT 'true' AFTER `destroyable`;

UPDATE `etcitem` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '4425');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6611');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6612');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6613');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6614');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6615');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6616');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6617');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6618');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6619');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6620');
UPDATE `weapon` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6621');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6408');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6656');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6657');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6658');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6659');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6660');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6661');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '6662');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6834');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6835');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6836');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6837');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6838');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6839');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6840');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '6841');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '7694');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '8182');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'false' WHERE (`item_id` = '8183');
UPDATE `armor` SET dropable = 'false', destroyable = 'false', tradeable = 'true' WHERE (`item_id` = '8191');
