ALTER TABLE items ADD mana_left DECIMAL( 3, 0 ) NOT NULL DEFAULT -1;
ALTER TABLE etcitem CHANGE COLUMN durability duration DECIMAL(3,0) DEFAULT NULL;
ALTER TABLE armor CHANGE COLUMN durability duration DECIMAL(3,0) DEFAULT NULL;
ALTER TABLE weapon CHANGE COLUMN durability duration DECIMAL(3,0) DEFAULT NULL;