-- MySQL Script generated by MySQL Workbench
-- Qua 11 Abr 2018 19:05:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema l2jdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `l2jdb` ;

-- -----------------------------------------------------
-- Schema l2jdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `l2jdb` DEFAULT CHARACTER SET latin1 ;
USE `l2jdb` ;

-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

CREATE TABLE IF NOT EXISTS `accounts` (
  `login` VARCHAR(45) NOT NULL DEFAULT '',
  `password` VARCHAR(45)  DEFAULT NULL,
  `lastactive` DECIMAL(20,0)  DEFAULT NULL,
  `access_level` INT  DEFAULT 0,
  `lastIP` VARCHAR(20)  DEFAULT NULL,
  `lastServer` INT NOT NULL DEFAULT 1,
  `newbieCharacterId` DECIMAL(11,0) NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `armor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armor` ;

CREATE TABLE IF NOT EXISTS `armor` (
  `item_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(70) NULL DEFAULT NULL,
  `bodypart` VARCHAR(15) NOT NULL DEFAULT '',
  `crystallizable` VARCHAR(5) NOT NULL DEFAULT '',
  `armor_type` VARCHAR(5) NOT NULL DEFAULT '',
  `weight` INT(5) NOT NULL DEFAULT '0',
  `material` VARCHAR(15) NOT NULL DEFAULT '',
  `crystal_type` VARCHAR(4) NOT NULL DEFAULT '',
  `avoid_modify` INT(1) NOT NULL DEFAULT '0',
  `duration` INT(3) NOT NULL DEFAULT '0',
  `p_def` INT(3) NOT NULL DEFAULT '0',
  `m_def` INT(2) NOT NULL DEFAULT '0',
  `mp_bonus` INT(3) NOT NULL DEFAULT '0',
  `price` INT(11) NOT NULL DEFAULT '0',
  `crystal_count` INT(4) NULL DEFAULT NULL,
  `sellable` VARCHAR(5) NULL DEFAULT NULL,
  `dropable` VARCHAR(5) NULL DEFAULT NULL,
  `destroyable` VARCHAR(5) NULL DEFAULT NULL,
  `tradeable` VARCHAR(5) NULL DEFAULT NULL,
  `item_skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `item_skill_lvl` DECIMAL(11,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `weapon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weapon` ;

CREATE TABLE IF NOT EXISTS `weapon` (
  `item_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `name` VARCHAR(70) NULL DEFAULT NULL,
  `bodypart` VARCHAR(15) NULL DEFAULT NULL,
  `crystallizable` VARCHAR(5) NULL DEFAULT NULL,
  `weight` DECIMAL(4,0) NULL DEFAULT NULL,
  `soulshots` DECIMAL(2,0) NULL DEFAULT NULL,
  `spiritshots` DECIMAL(1,0) NULL DEFAULT NULL,
  `material` VARCHAR(11) NULL DEFAULT NULL,
  `crystal_type` VARCHAR(4) NULL DEFAULT NULL,
  `p_dam` DECIMAL(5,0) NULL DEFAULT NULL,
  `rnd_dam` DECIMAL(2,0) NULL DEFAULT NULL,
  `weaponType` VARCHAR(8) NULL DEFAULT NULL,
  `critical` DECIMAL(2,0) NULL DEFAULT NULL,
  `hit_modify` DECIMAL(6,5) NULL DEFAULT NULL,
  `avoid_modify` DECIMAL(2,0) NULL DEFAULT NULL,
  `shield_def` DECIMAL(3,0) NULL DEFAULT NULL,
  `shield_def_rate` DECIMAL(2,0) NULL DEFAULT NULL,
  `atk_speed` DECIMAL(3,0) NULL DEFAULT NULL,
  `mp_consume` DECIMAL(2,0) NULL DEFAULT NULL,
  `m_dam` DECIMAL(3,0) NULL DEFAULT NULL,
  `duration` DECIMAL(3,0) NULL DEFAULT NULL,
  `price` DECIMAL(11,0) NULL DEFAULT NULL,
  `crystal_count` INT(4) NULL DEFAULT NULL,
  `sellable` VARCHAR(5) NULL DEFAULT NULL,
  `dropable` VARCHAR(5) NULL DEFAULT NULL,
  `destroyable` VARCHAR(5) NULL DEFAULT NULL,
  `tradeable` VARCHAR(5) NULL DEFAULT NULL,
  `item_skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `item_skill_lvl` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `enchant4_skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `enchant4_skill_lvl` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `onCast_skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `onCast_skill_lvl` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `onCast_skill_chance` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `onCrit_skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `onCrit_skill_lvl` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `onCrit_skill_chance` DECIMAL(11,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `armorsets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `armorsets` ;

CREATE TABLE IF NOT EXISTS `armorsets` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `chest` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `legs` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `head` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `gloves` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `feet` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `shield` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `shield_skill_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `enchant6skill` DECIMAL(11,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`, `chest`),
  INDEX `fk_armorsets_armor1_idx` (`chest` ASC),
  INDEX `fk_armorsets_armor2_idx` (`legs` ASC),
  INDEX `fk_armorsets_armor3_idx` (`head` ASC),
  INDEX `fk_armorsets_armor4_idx` (`gloves` ASC),
  INDEX `fk_armorsets_armor5_idx` (`feet` ASC),
  INDEX `fk_armorsets_weapon1_idx` (`shield` ASC),
  CONSTRAINT `fk_armorsets_armor1`
    FOREIGN KEY (`chest`)
    REFERENCES `armor` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armorsets_armor2`
    FOREIGN KEY (`legs`)
    REFERENCES `armor` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armorsets_armor3`
    FOREIGN KEY (`head`)
    REFERENCES `armor` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armorsets_armor4`
    FOREIGN KEY (`gloves`)
    REFERENCES `armor` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armorsets_armor5`
    FOREIGN KEY (`feet`)
    REFERENCES `armor` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armorsets_weapon1`
    FOREIGN KEY (`shield`)
    REFERENCES `weapon` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `char_templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `char_templates` ;

CREATE TABLE IF NOT EXISTS `char_templates` (
  `ClassId` INT(11) NOT NULL DEFAULT '0',
  `ClassName` VARCHAR(20) NOT NULL DEFAULT '',
  `RaceId` INT(1) NOT NULL DEFAULT '0',
  `STR` INT(2) NOT NULL DEFAULT '0',
  `CON` INT(2) NOT NULL DEFAULT '0',
  `DEX` INT(2) NOT NULL DEFAULT '0',
  `_INT` INT(2) NOT NULL DEFAULT '0',
  `WIT` INT(2) NOT NULL DEFAULT '0',
  `MEN` INT(2) NOT NULL DEFAULT '0',
  `P_ATK` INT(3) NOT NULL DEFAULT '0',
  `P_DEF` INT(3) NOT NULL DEFAULT '0',
  `M_ATK` INT(3) NOT NULL DEFAULT '0',
  `M_DEF` INT(2) NOT NULL DEFAULT '0',
  `P_SPD` INT(3) NOT NULL DEFAULT '0',
  `M_SPD` INT(3) NOT NULL DEFAULT '0',
  `ACC` INT(3) NOT NULL DEFAULT '0',
  `CRITICAL` INT(3) NOT NULL DEFAULT '0',
  `EVASION` INT(3) NOT NULL DEFAULT '0',
  `MOVE_SPD` INT(3) NOT NULL DEFAULT '0',
  `_LOAD` INT(11) NOT NULL DEFAULT '0',
  `x` INT(9) NOT NULL DEFAULT '0',
  `y` INT(9) NOT NULL DEFAULT '0',
  `z` INT(9) NOT NULL DEFAULT '0',
  `canCraft` INT(1) NOT NULL DEFAULT '0',
  `M_UNK1` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `M_UNK2` DECIMAL(8,6) NOT NULL DEFAULT '0.000000',
  `M_COL_R` DECIMAL(3,1) NOT NULL DEFAULT '0.0',
  `M_COL_H` DECIMAL(4,1) NOT NULL DEFAULT '0.0',
  `F_UNK1` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `F_UNK2` DECIMAL(8,6) NOT NULL DEFAULT '0.000000',
  `F_COL_R` DECIMAL(3,1) NOT NULL DEFAULT '0.0',
  `F_COL_H` DECIMAL(4,1) NOT NULL DEFAULT '0.0',
  `items1` INT(4) NOT NULL DEFAULT '0',
  `items2` INT(4) NOT NULL DEFAULT '0',
  `items3` INT(4) NOT NULL DEFAULT '0',
  `items4` INT(4) NOT NULL DEFAULT '0',
  `items5` INT(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ClassId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `characters` ;

CREATE TABLE IF NOT EXISTS `characters` (
  `account_name` VARCHAR(45) NULL DEFAULT NULL,
  `obj_Id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `char_name` VARCHAR(35) NOT NULL,
  `level` DECIMAL(11,0) NULL DEFAULT NULL,
  `maxHp` DECIMAL(11,0) NULL DEFAULT NULL,
  `curHp` DECIMAL(18,0) NULL DEFAULT NULL,
  `maxCp` DECIMAL(11,0) NULL DEFAULT NULL,
  `curCp` DECIMAL(18,0) NULL DEFAULT NULL,
  `maxMp` DECIMAL(11,0) NULL DEFAULT NULL,
  `curMp` DECIMAL(18,0) NULL DEFAULT NULL,
  `acc` DECIMAL(11,0) NULL DEFAULT NULL,
  `crit` DECIMAL(10,0) NULL DEFAULT NULL,
  `evasion` DECIMAL(11,0) NULL DEFAULT NULL,
  `mAtk` DECIMAL(11,0) NULL DEFAULT NULL,
  `mDef` DECIMAL(11,0) NULL DEFAULT NULL,
  `mSpd` DECIMAL(11,0) NULL DEFAULT NULL,
  `pAtk` DECIMAL(11,0) NULL DEFAULT NULL,
  `pDef` DECIMAL(11,0) NULL DEFAULT NULL,
  `pSpd` DECIMAL(11,0) NULL DEFAULT NULL,
  `runSpd` DECIMAL(11,0) NULL DEFAULT NULL,
  `walkSpd` DECIMAL(11,0) NULL DEFAULT NULL,
  `str` DECIMAL(11,0) NULL DEFAULT NULL,
  `con` DECIMAL(11,0) NULL DEFAULT NULL,
  `dex` DECIMAL(11,0) NULL DEFAULT NULL,
  `_int` DECIMAL(11,0) NULL DEFAULT NULL,
  `men` DECIMAL(11,0) NULL DEFAULT NULL,
  `wit` DECIMAL(11,0) NULL DEFAULT NULL,
  `face` DECIMAL(11,0) NULL DEFAULT NULL,
  `hairStyle` DECIMAL(11,0) NULL DEFAULT NULL,
  `hairColor` DECIMAL(11,0) NULL DEFAULT NULL,
  `sex` DECIMAL(11,0) NULL DEFAULT NULL,
  `heading` DECIMAL(11,0) NULL DEFAULT NULL,
  `x` DECIMAL(11,0) NULL DEFAULT NULL,
  `y` DECIMAL(11,0) NULL DEFAULT NULL,
  `z` DECIMAL(11,0) NULL DEFAULT NULL,
  `movement_multiplier` DECIMAL(9,8) NULL DEFAULT NULL,
  `attack_speed_multiplier` DECIMAL(10,9) NULL DEFAULT NULL,
  `colRad` DECIMAL(10,3) NULL DEFAULT NULL,
  `colHeight` DECIMAL(10,3) NULL DEFAULT NULL,
  `exp` DECIMAL(20,0) NULL DEFAULT NULL,
  `expBeforeDeath` DECIMAL(20,0) NULL DEFAULT '0',
  `sp` DECIMAL(11,0) NULL DEFAULT NULL,
  `karma` DECIMAL(11,0) NULL DEFAULT NULL,
  `pvpkills` DECIMAL(11,0) NULL DEFAULT NULL,
  `pkkills` DECIMAL(11,0) NULL DEFAULT NULL,
  `clanid` DECIMAL(11,0) NULL DEFAULT NULL,
  `maxload` DECIMAL(11,0) NULL DEFAULT NULL,
  `race` DECIMAL(11,0) NULL DEFAULT NULL,
  `classid` DECIMAL(11,0) NULL DEFAULT NULL,
  `base_class` INT(2) NOT NULL DEFAULT '0',
  `deletetime` DECIMAL(20,0) NULL DEFAULT NULL,
  `cancraft` DECIMAL(11,0) NULL DEFAULT NULL,
  `title` VARCHAR(16) NULL DEFAULT NULL,
  `rec_have` INT(3) NOT NULL DEFAULT '0',
  `rec_left` INT(3) NOT NULL DEFAULT '0',
  `accesslevel` DECIMAL(4,0) NULL DEFAULT NULL,
  `online` DECIMAL(1,0) NULL DEFAULT NULL,
  `onlinetime` DECIMAL(20,0) NULL DEFAULT NULL,
  `char_slot` DECIMAL(1,0) NULL DEFAULT NULL,
  `newbie` DECIMAL(1,0) NULL DEFAULT '1',
  `lastAccess` DECIMAL(20,0) NULL DEFAULT NULL,
  `clan_privs` INT(11) NULL DEFAULT '0',
  `wantspeace` DECIMAL(1,0) NULL DEFAULT '0',
  `isin7sdungeon` DECIMAL(1,0) NOT NULL DEFAULT '0',
  `in_jail` DECIMAL(1,0) NULL DEFAULT '0',
  `jail_timer` DECIMAL(20,0) NULL DEFAULT '0',
  `power_grade` DECIMAL(11,0) NULL DEFAULT NULL,
  `nobless` DECIMAL(1,0) NOT NULL DEFAULT '0',
  `subpledge` INT(1) NOT NULL DEFAULT '0',
  `last_recom_date` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `lvl_joined_academy` INT(1) NOT NULL DEFAULT '0',
  `apprentice` INT(1) NOT NULL DEFAULT '0',
  `sponsor` INT(1) NOT NULL DEFAULT '0',
  `varka_ketra_ally` INT(1) NOT NULL DEFAULT '0',
  `clan_join_expiry_time` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `clan_create_expiry_time` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `death_penalty_level` INT(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`obj_Id`),
  INDEX `clanid` (`clanid` ASC),
  INDEX `fk_characters_accounts1_idx` (`account_name` ASC),
  INDEX `fk_characters_char_templates1_idx` (`classid` ASC),
  CONSTRAINT `fk_characters_accounts1`
    FOREIGN KEY (`account_name`)
    REFERENCES `accounts` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_char_templates1`
    FOREIGN KEY (`classid`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clan_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clan_data` ;

CREATE TABLE IF NOT EXISTS `clan_data` (
  `clan_id` INT(11) NOT NULL DEFAULT '0',
  `clan_name` VARCHAR(45) NULL DEFAULT NULL,
  `clan_level` INT(11) NULL DEFAULT NULL,
  `reputation_score` INT(11) NOT NULL DEFAULT '0',
  `hasCastle` INT(11) NULL DEFAULT NULL,
  `ally_id` INT(11) NULL DEFAULT NULL,
  `ally_name` VARCHAR(45) NULL DEFAULT NULL,
  `leader_id` INT(11) NULL DEFAULT NULL,
  `crest_id` INT(11) NULL DEFAULT NULL,
  `crest_large_id` INT(11) NULL DEFAULT NULL,
  `ally_crest_id` INT(11) NULL DEFAULT NULL,
  `auction_bid_at` INT(11) NOT NULL DEFAULT '0',
  `ally_penalty_expiry_time` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `ally_penalty_type` DECIMAL(1,0) NOT NULL DEFAULT '0',
  `char_penalty_expiry_time` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `dissolving_expiry_time` DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`clan_id`),
  INDEX `leader_id` (`leader_id` ASC),
  INDEX `ally_id` (`ally_id` ASC),
  CONSTRAINT `fk_clan_data_characters1`
    FOREIGN KEY (`leader_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clanhall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clanhall` ;

CREATE TABLE IF NOT EXISTS `clanhall` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(40) NOT NULL DEFAULT '',
  `ownerId` INT(11) NOT NULL DEFAULT '0',
  `lease` INT(10) NOT NULL DEFAULT '0',
  `desc` TEXT NOT NULL,
  `location` VARCHAR(15) NOT NULL DEFAULT '',
  `paidUntil` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `Grade` DECIMAL(1,0) NOT NULL DEFAULT '0',
  `paid` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_clanhall_clan_data1_idx` (`ownerId` ASC),
  CONSTRAINT `fk_clanhall_clan_data1`
    FOREIGN KEY (`ownerId`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auction` ;

CREATE TABLE IF NOT EXISTS `auction` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `sellerId` INT(11) NOT NULL DEFAULT '0',
  `sellerName` VARCHAR(50) NOT NULL DEFAULT 'NPC',
  `sellerClanName` VARCHAR(50) NOT NULL DEFAULT '',
  `itemType` VARCHAR(25) NOT NULL DEFAULT '',
  `itemId` INT(11) NOT NULL DEFAULT '0',
  `itemObjectId` INT(11) NOT NULL DEFAULT '0',
  `itemName` VARCHAR(40) NOT NULL DEFAULT '',
  `itemQuantity` INT(11) NOT NULL DEFAULT '0',
  `startingBid` INT(11) NOT NULL DEFAULT '0',
  `currentBid` INT(11) NOT NULL DEFAULT '0',
  `endDate` DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`itemType`, `itemId`, `itemObjectId`),
  INDEX `id` (`id` ASC),
  INDEX `fk_auction_clanhall1_idx` (`itemId` ASC),
  CONSTRAINT `fk_auction_clanhall1`
    FOREIGN KEY (`itemId`)
    REFERENCES `clanhall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auction_bid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auction_bid` ;

CREATE TABLE IF NOT EXISTS `auction_bid` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `auctionId` INT(11) NOT NULL DEFAULT '0',
  `bidderId` INT(11) NOT NULL DEFAULT '0',
  `bidderName` VARCHAR(50) NOT NULL,
  `clan_name` VARCHAR(50) NOT NULL,
  `maxBid` INT(11) NOT NULL DEFAULT '0',
  `time_bid` DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`auctionId`, `bidderId`),
  INDEX `id` (`id` ASC),
  INDEX `fk_auction_bid_clan_data1_idx` (`bidderId` ASC),
  CONSTRAINT `fk_auction_bid_auction1`
    FOREIGN KEY (`auctionId`)
    REFERENCES `auction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auction_bid_clan_data1`
    FOREIGN KEY (`bidderId`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auction_watch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auction_watch` ;

CREATE TABLE IF NOT EXISTS `auction_watch` (
  `charObjId` INT(11) NOT NULL DEFAULT '0',
  `auctionId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`charObjId`, `auctionId`),
  INDEX `fk_auction_watch_auction1_idx` (`auctionId` ASC),
  CONSTRAINT `fk_auction_watch_auction1`
    FOREIGN KEY (`auctionId`)
    REFERENCES `auction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auction_watch_characters1`
    FOREIGN KEY (`charObjId`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `augmentations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `augmentations` ;

CREATE TABLE IF NOT EXISTS `augmentations` (
  `item_id` INT(11) NOT NULL DEFAULT '0',
  `attributes` INT(11) NULL DEFAULT '0',
  `skill` INT(11) NULL DEFAULT '0',
  `level` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_augmentations_weapon1`
    FOREIGN KEY (`item_id`)
    REFERENCES `weapon` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `npc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `npc` ;

CREATE TABLE IF NOT EXISTS `npc` (
  `id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `idTemplate` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `serverSideName` INT(1) NULL DEFAULT '0',
  `title` VARCHAR(45) NULL DEFAULT '',
  `serverSideTitle` INT(1) NULL DEFAULT '0',
  `class` VARCHAR(200) NULL DEFAULT NULL,
  `collision_radius` DECIMAL(5,2) NULL DEFAULT NULL,
  `collision_height` DECIMAL(5,2) NULL DEFAULT NULL,
  `level` DECIMAL(2,0) NULL DEFAULT NULL,
  `sex` VARCHAR(6) NULL DEFAULT NULL,
  `type` VARCHAR(20) NULL DEFAULT NULL,
  `attackrange` INT(11) NULL DEFAULT NULL,
  `hp` DECIMAL(8,0) NULL DEFAULT NULL,
  `mp` DECIMAL(5,0) NULL DEFAULT NULL,
  `hpreg` DECIMAL(8,2) NULL DEFAULT NULL,
  `mpreg` DECIMAL(5,2) NULL DEFAULT NULL,
  `str` DECIMAL(7,0) NULL DEFAULT NULL,
  `con` DECIMAL(7,0) NULL DEFAULT NULL,
  `dex` DECIMAL(7,0) NULL DEFAULT NULL,
  `int` DECIMAL(7,0) NULL DEFAULT NULL,
  `wit` DECIMAL(7,0) NULL DEFAULT NULL,
  `men` DECIMAL(7,0) NULL DEFAULT NULL,
  `exp` DECIMAL(9,0) NULL DEFAULT NULL,
  `sp` DECIMAL(8,0) NULL DEFAULT NULL,
  `patk` DECIMAL(5,0) NULL DEFAULT NULL,
  `pdef` DECIMAL(5,0) NULL DEFAULT NULL,
  `matk` DECIMAL(5,0) NULL DEFAULT NULL,
  `mdef` DECIMAL(5,0) NULL DEFAULT NULL,
  `atkspd` DECIMAL(3,0) NULL DEFAULT NULL,
  `aggro` DECIMAL(6,0) NULL DEFAULT NULL,
  `matkspd` DECIMAL(4,0) NULL DEFAULT NULL,
  `rhand` DECIMAL(4,0) NULL DEFAULT NULL,
  `lhand` DECIMAL(4,0) NULL DEFAULT NULL,
  `armor` DECIMAL(1,0) NULL DEFAULT NULL,
  `walkspd` DECIMAL(3,0) NULL DEFAULT NULL,
  `runspd` DECIMAL(3,0) NULL DEFAULT NULL,
  `faction_id` VARCHAR(40) NULL DEFAULT NULL,
  `faction_range` DECIMAL(4,0) NULL DEFAULT NULL,
  `isUndead` INT(11) NULL DEFAULT '0',
  `absorb_level` DECIMAL(2,0) NULL DEFAULT '0',
  `absorb_type` ENUM('FULL_PARTY', 'LAST_HIT', 'PARTY_ONE_RANDOM') NOT NULL DEFAULT 'LAST_HIT',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auto_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_chat` ;

CREATE TABLE IF NOT EXISTS `auto_chat` (
  `groupId` INT(11) NOT NULL DEFAULT '0',
  `npcId` INT(11) NOT NULL DEFAULT '0',
  `chatDelay` BIGINT(20) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`groupId`),
  INDEX `fk_auto_chat_npc1_idx` (`npcId` ASC),
  CONSTRAINT `fk_auto_chat_npc1`
    FOREIGN KEY (`npcId`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auto_chat_text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auto_chat_text` ;

CREATE TABLE IF NOT EXISTS `auto_chat_text` (
  `groupId` INT(11) NOT NULL DEFAULT '0',
  `chatText` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`groupId`, `chatText`),
  CONSTRAINT `fk_auto_chat_text_auto_chat1`
    FOREIGN KEY (`groupId`)
    REFERENCES `auto_chat` (`groupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `boxaccess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boxaccess` ;

CREATE TABLE IF NOT EXISTS `boxaccess` (
  `spawn` DECIMAL(11,0) NULL DEFAULT NULL,
  `charname` VARCHAR(32) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `boxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boxes` ;

CREATE TABLE IF NOT EXISTS `boxes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `spawn` DECIMAL(11,0) NULL DEFAULT NULL,
  `npcid` DECIMAL(11,0) NULL DEFAULT NULL,
  `drawer` VARCHAR(32) NULL DEFAULT NULL,
  `itemid` DECIMAL(11,0) NULL DEFAULT NULL,
  `name` VARCHAR(32) NULL DEFAULT '',
  `count` DECIMAL(11,0) NULL DEFAULT NULL,
  `enchant` DECIMAL(2,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castle` ;

CREATE TABLE IF NOT EXISTS `castle` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(25) NOT NULL,
  `taxPercent` INT(11) NOT NULL DEFAULT '15',
  `treasury` INT(11) NOT NULL DEFAULT '0',
  `siegeDate` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `siegeDayOfWeek` INT(11) NOT NULL DEFAULT '7',
  `siegeHourOfDay` INT(11) NOT NULL DEFAULT '20',
  PRIMARY KEY (`name`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castle_door`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castle_door` ;

CREATE TABLE IF NOT EXISTS `castle_door` (
  `castleId` INT(11) NOT NULL DEFAULT '0',
  `id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(30) NOT NULL,
  `x` INT(11) NOT NULL DEFAULT '0',
  `y` INT(11) NOT NULL DEFAULT '0',
  `z` INT(11) NOT NULL DEFAULT '0',
  `range_xmin` INT(11) NOT NULL DEFAULT '0',
  `range_ymin` INT(11) NOT NULL DEFAULT '0',
  `range_zmin` INT(11) NOT NULL DEFAULT '0',
  `range_xmax` INT(11) NOT NULL DEFAULT '0',
  `range_ymax` INT(11) NOT NULL DEFAULT '0',
  `range_zmax` INT(11) NOT NULL DEFAULT '0',
  `hp` INT(11) NOT NULL DEFAULT '0',
  `pDef` INT(11) NOT NULL DEFAULT '0',
  `mDef` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `id` (`castleId` ASC),
  CONSTRAINT `fk_castle_door_castle1`
    FOREIGN KEY (`castleId`)
    REFERENCES `castle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castle_doorupgrade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castle_doorupgrade` ;

CREATE TABLE IF NOT EXISTS `castle_doorupgrade` (
  `doorId` INT(11) NOT NULL DEFAULT '0',
  `hp` INT(11) NOT NULL DEFAULT '0',
  `pDef` INT(11) NOT NULL DEFAULT '0',
  `mDef` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`doorId`),
  CONSTRAINT `fk_castle_doorupgrade_castle_door1`
    FOREIGN KEY (`doorId`)
    REFERENCES `castle_door` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castle_manor_procure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castle_manor_procure` ;

CREATE TABLE IF NOT EXISTS `castle_manor_procure` (
  `castle_id` INT(11) NOT NULL DEFAULT '0',
  `crop_id` INT(11) NOT NULL DEFAULT '0',
  `can_buy` INT(11) NOT NULL DEFAULT '0',
  `start_buy` INT(11) NOT NULL DEFAULT '0',
  `price` INT(11) NOT NULL DEFAULT '0',
  `reward_type` INT(11) NOT NULL DEFAULT '0',
  `period` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`castle_id`, `crop_id`, `period`),
  CONSTRAINT `fk_castle_manor_procure_castle1`
    FOREIGN KEY (`castle_id`)
    REFERENCES `castle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castle_manor_production`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castle_manor_production` ;

CREATE TABLE IF NOT EXISTS `castle_manor_production` (
  `castle_id` INT(11) NOT NULL DEFAULT '0',
  `seed_id` INT(11) NOT NULL DEFAULT '0',
  `can_produce` INT(11) NOT NULL DEFAULT '0',
  `start_produce` INT(11) NOT NULL DEFAULT '0',
  `seed_price` INT(11) NOT NULL DEFAULT '0',
  `period` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`castle_id`, `seed_id`, `period`),
  CONSTRAINT `fk_castle_manor_production_castle1`
    FOREIGN KEY (`castle_id`)
    REFERENCES `castle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `castle_siege_guards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `castle_siege_guards` ;

CREATE TABLE IF NOT EXISTS `castle_siege_guards` (
  `castleId` INT(11) NOT NULL DEFAULT '0',
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `npcId` INT(11) NOT NULL DEFAULT '0',
  `x` INT(11) NOT NULL DEFAULT '0',
  `y` INT(11) NOT NULL DEFAULT '0',
  `z` INT(11) NOT NULL DEFAULT '0',
  `heading` INT(11) NOT NULL DEFAULT '0',
  `respawnDelay` INT(11) NOT NULL DEFAULT '0',
  `isHired` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `id` (`castleId` ASC),
  INDEX `fk_castle_siege_guards_npc1_idx` (`npcId` ASC),
  CONSTRAINT `fk_castle_siege_guards_castle1`
    FOREIGN KEY (`castleId`)
    REFERENCES `castle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_castle_siege_guards_npc1`
    FOREIGN KEY (`npcId`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3448
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_friends` ;

CREATE TABLE IF NOT EXISTS `character_friends` (
  `char_id` INT(11) NOT NULL DEFAULT '0',
  `friend_id` INT(11) NOT NULL DEFAULT '0',
  `friend_name` VARCHAR(35) NOT NULL DEFAULT '',
  PRIMARY KEY (`char_id`, `friend_name`),
  INDEX `fk_character_friends_characters2_idx` (`friend_id` ASC),
  CONSTRAINT `fk_character_friends_characters1`
    FOREIGN KEY (`char_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_friends_characters2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `etcitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etcitem` ;

CREATE TABLE IF NOT EXISTS `etcitem` (
  `item_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `crystallizable` VARCHAR(5) NULL DEFAULT NULL,
  `item_type` VARCHAR(15) NULL DEFAULT NULL,
  `weight` DECIMAL(4,0) NULL DEFAULT NULL,
  `consume_type` VARCHAR(9) NULL DEFAULT NULL,
  `material` VARCHAR(11) NULL DEFAULT NULL,
  `crystal_type` VARCHAR(4) NULL DEFAULT NULL,
  `duration` DECIMAL(3,0) NULL DEFAULT NULL,
  `price` DECIMAL(11,0) NULL DEFAULT NULL,
  `crystal_count` INT(4) NULL DEFAULT NULL,
  `sellable` VARCHAR(5) NULL DEFAULT NULL,
  `dropable` VARCHAR(5) NULL DEFAULT NULL,
  `destroyable` VARCHAR(5) NULL DEFAULT NULL,
  `tradeable` VARCHAR(5) NULL DEFAULT NULL,
  `oldname` VARCHAR(100) NOT NULL DEFAULT '',
  `oldtype` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `henna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `henna` ;

CREATE TABLE IF NOT EXISTS `henna` (
  `symbol_id` INT(11) NOT NULL DEFAULT '0',
  `symbol_name` VARCHAR(45) NULL DEFAULT NULL,
  `dye_id` INT(11) NULL DEFAULT NULL,
  `dye_amount` INT(11) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `stat_INT` DECIMAL(11,0) NULL DEFAULT NULL,
  `stat_STR` DECIMAL(11,0) NULL DEFAULT NULL,
  `stat_CON` DECIMAL(11,0) NULL DEFAULT NULL,
  `stat_MEM` DECIMAL(11,0) NULL DEFAULT NULL,
  `stat_DEX` DECIMAL(11,0) NULL DEFAULT NULL,
  `stat_WIT` DECIMAL(11,0) NULL DEFAULT NULL,
  PRIMARY KEY (`symbol_id`),
  INDEX `fk_henna_etcitem1_idx` (`dye_id` ASC),
  CONSTRAINT `fk_henna_etcitem1`
    FOREIGN KEY (`dye_id`)
    REFERENCES `etcitem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_hennas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_hennas` ;

CREATE TABLE IF NOT EXISTS `character_hennas` (
  `char_obj_id` INT(11) NOT NULL DEFAULT '0',
  `symbol_id` INT(11) NULL DEFAULT NULL,
  `slot` INT(11) NOT NULL DEFAULT '0',
  `class_index` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_obj_id`, `slot`, `class_index`),
  INDEX `fk_character_hennas_henna1_idx` (`symbol_id` ASC),
  CONSTRAINT `fk_character_hennas_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_hennas_henna1`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `henna` (`symbol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_macroses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_macroses` ;

CREATE TABLE IF NOT EXISTS `character_macroses` (
  `char_obj_id` INT(11) NOT NULL DEFAULT '0',
  `id` INT(11) NOT NULL DEFAULT '0',
  `icon` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(40) NULL DEFAULT NULL,
  `descr` VARCHAR(80) NULL DEFAULT NULL,
  `acronym` VARCHAR(4) NULL DEFAULT NULL,
  `commands` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`char_obj_id`, `id`),
  CONSTRAINT `fk_character_macroses_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_quests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_quests` ;

CREATE TABLE IF NOT EXISTS `character_quests` (
  `char_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(40) NOT NULL DEFAULT '',
  `var` VARCHAR(20) NOT NULL DEFAULT '',
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `class_index` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`, `name`, `var`, `class_index`),
  CONSTRAINT `fk_character_quests_characters1`
    FOREIGN KEY (`char_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_recipebook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_recipebook` ;

CREATE TABLE IF NOT EXISTS `character_recipebook` (
  `char_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `type` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`, `char_id`),
  INDEX `fk_character_recipebook_characters1_idx` (`char_id` ASC),
  CONSTRAINT `fk_character_recipebook_characters1`
    FOREIGN KEY (`char_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_recommends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_recommends` ;

CREATE TABLE IF NOT EXISTS `character_recommends` (
  `char_id` INT(11) NOT NULL DEFAULT '0',
  `target_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`, `target_id`),
  INDEX `fk_character_recommends_characters2_idx` (`target_id` ASC),
  CONSTRAINT `fk_character_recommends_characters1`
    FOREIGN KEY (`char_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_recommends_characters2`
    FOREIGN KEY (`target_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_shortcuts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_shortcuts` ;

CREATE TABLE IF NOT EXISTS `character_shortcuts` (
  `char_obj_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `slot` DECIMAL(3,0) NOT NULL DEFAULT '0',
  `page` DECIMAL(3,0) NOT NULL DEFAULT '0',
  `type` DECIMAL(3,0) NULL DEFAULT NULL,
  `shortcut_id` DECIMAL(16,0) NULL DEFAULT NULL,
  `level` VARCHAR(4) NULL DEFAULT NULL,
  `class_index` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_obj_id`, `slot`, `page`, `class_index`),
  INDEX `shortcut_id` (`shortcut_id` ASC),
  CONSTRAINT `fk_character_shortcuts_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_skills` ;

CREATE TABLE IF NOT EXISTS `character_skills` (
  `char_obj_id` INT(11) NOT NULL DEFAULT '0',
  `skill_id` INT(11) NOT NULL DEFAULT '0',
  `skill_level` VARCHAR(5) NULL DEFAULT NULL,
  `skill_name` VARCHAR(40) NULL DEFAULT NULL,
  `class_index` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_obj_id`, `skill_id`, `class_index`),
  CONSTRAINT `fk_character_skills_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_skills_save`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_skills_save` ;

CREATE TABLE IF NOT EXISTS `character_skills_save` (
  `char_obj_id` INT(11) NOT NULL DEFAULT '0',
  `skill_id` INT(11) NOT NULL DEFAULT '0',
  `skill_level` INT(11) NOT NULL DEFAULT '0',
  `effect_count` INT(11) NOT NULL DEFAULT '0',
  `effect_cur_time` INT(11) NOT NULL DEFAULT '0',
  `reuse_delay` INT(8) NOT NULL DEFAULT '0',
  `restore_type` INT(1) NOT NULL DEFAULT '0',
  `class_index` INT(1) NOT NULL DEFAULT '0',
  `buff_index` INT(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_obj_id`, `skill_id`, `class_index`),
  CONSTRAINT `fk_character_skills_save_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `character_subclasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_subclasses` ;

CREATE TABLE IF NOT EXISTS `character_subclasses` (
  `char_obj_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `class_id` INT(2) NOT NULL DEFAULT '0',
  `exp` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `sp` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `level` INT(2) NOT NULL DEFAULT '40',
  `class_index` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_obj_id`, `class_id`),
  INDEX `fk_character_subclasses_char_templates1_idx` (`class_id` ASC),
  CONSTRAINT `fk_character_subclasses_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_subclasses_char_templates1`
    FOREIGN KEY (`class_id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clan_privs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clan_privs` ;

CREATE TABLE IF NOT EXISTS `clan_privs` (
  `clan_id` INT(11) NOT NULL DEFAULT '0',
  `rank` INT(11) NOT NULL DEFAULT '0',
  `party` INT(11) NOT NULL DEFAULT '0',
  `privs` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`clan_id`, `rank`, `party`),
  CONSTRAINT `fk_clan_privs_clan_data1`
    FOREIGN KEY (`clan_id`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clan_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clan_skills` ;

CREATE TABLE IF NOT EXISTS `clan_skills` (
  `clan_id` INT(11) NOT NULL DEFAULT '0',
  `skill_id` INT(11) NOT NULL DEFAULT '0',
  `skill_level` INT(5) NOT NULL DEFAULT '0',
  `skill_name` VARCHAR(26) NULL DEFAULT NULL,
  PRIMARY KEY (`clan_id`, `skill_id`),
  CONSTRAINT `fk_clan_skills_clan_data1`
    FOREIGN KEY (`clan_id`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clan_subpledges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clan_subpledges` ;

CREATE TABLE IF NOT EXISTS `clan_subpledges` (
  `clan_id` INT(11) NOT NULL DEFAULT '0',
  `sub_pledge_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `leader_name` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`clan_id`, `sub_pledge_id`),
  CONSTRAINT `fk_clan_subpledges_clan_data1`
    FOREIGN KEY (`clan_id`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clan_wars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clan_wars` ;

CREATE TABLE IF NOT EXISTS `clan_wars` (
  `clan1` VARCHAR(35) NOT NULL DEFAULT '',
  `clan2` VARCHAR(35) NOT NULL DEFAULT '',
  `wantspeace1` DECIMAL(1,0) NOT NULL DEFAULT '0',
  `wantspeace2` DECIMAL(1,0) NOT NULL DEFAULT '0',
  INDEX `fk_clan_wars_clan_data1_idx` (`clan1` ASC),
  INDEX `fk_clan_wars_clan_data2_idx` (`clan2` ASC),
  CONSTRAINT `fk_clan_wars_clan_data1`
    FOREIGN KEY (`clan1`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clan_wars_clan_data2`
    FOREIGN KEY (`clan2`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `clanhall_functions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clanhall_functions` ;

CREATE TABLE IF NOT EXISTS `clanhall_functions` (
  `hall_id` INT(2) NOT NULL DEFAULT '0',
  `type` INT(1) NOT NULL DEFAULT '0',
  `lvl` INT(3) NOT NULL DEFAULT '0',
  `lease` INT(10) NOT NULL DEFAULT '0',
  `rate` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `endTime` DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`hall_id`, `type`),
  CONSTRAINT `fk_clanhall_functions_clanhall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `clanhall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `class_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `class_list` ;

CREATE TABLE IF NOT EXISTS `class_list` (
  `class_name` VARCHAR(19) NOT NULL DEFAULT '',
  `id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `parent_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_class_list_char_templates1`
    FOREIGN KEY (`id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cursed_weapons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursed_weapons` ;

CREATE TABLE IF NOT EXISTS `cursed_weapons` (
  `itemId` INT(11) NOT NULL,
  `playerId` INT(11) NULL DEFAULT '0',
  `playerKarma` INT(11) NULL DEFAULT '0',
  `playerPkKills` INT(11) NULL DEFAULT '0',
  `nbKills` INT(11) NULL DEFAULT '0',
  `endTime` DECIMAL(20,0) NULL DEFAULT '0',
  PRIMARY KEY (`itemId`),
  CONSTRAINT `fk_cursed_weapons_weapon1`
    FOREIGN KEY (`itemId`)
    REFERENCES `weapon` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dimensional_rift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dimensional_rift` ;

CREATE TABLE IF NOT EXISTS `dimensional_rift` (
  `type` TINYINT(1) NOT NULL,
  `room_id` TINYINT(1) NOT NULL,
  `xMin` INT(11) NOT NULL,
  `xMax` INT(11) NOT NULL,
  `yMin` INT(11) NOT NULL,
  `yMax` INT(11) NOT NULL,
  `zMin` INT(11) NOT NULL,
  `zMax` INT(11) NOT NULL,
  `xT` INT(11) NOT NULL,
  `yT` INT(11) NOT NULL,
  `zT` INT(11) NOT NULL,
  `boss` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`type`, `room_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `droplist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `droplist` ;

CREATE TABLE IF NOT EXISTS `droplist` (
  `mobId` INT(11) NOT NULL DEFAULT '0',
  `itemId` INT(11) NOT NULL DEFAULT '0',
  `min` INT(11) NOT NULL DEFAULT '0',
  `max` INT(11) NOT NULL DEFAULT '0',
  `category` INT(11) NOT NULL DEFAULT '0',
  `chance` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mobId`, `itemId`, `category`),
  INDEX `key_mobId` (`mobId` ASC),
  CONSTRAINT `fk_droplist_npc1`
    FOREIGN KEY (`mobId`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `enchant_skill_trees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enchant_skill_trees` ;

CREATE TABLE IF NOT EXISTS `enchant_skill_trees` (
  `skill_id` INT(10) NOT NULL DEFAULT '0',
  `level` INT(10) NOT NULL DEFAULT '0',
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `base_lvl` INT(2) NOT NULL DEFAULT '0',
  `enchant_type` VARCHAR(25) NULL DEFAULT NULL,
  `sp` INT(10) NOT NULL DEFAULT '0',
  `exp` INT(20) NULL DEFAULT NULL,
  `min_skill_lvl` INT(2) NOT NULL DEFAULT '0',
  `success_rate76` INT(3) UNSIGNED NOT NULL DEFAULT '0',
  `success_rate77` INT(3) NOT NULL DEFAULT '0',
  `success_rate78` INT(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`skill_id`, `level`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fish` ;

CREATE TABLE IF NOT EXISTS `fish` (
  `id` INT(5) NOT NULL DEFAULT '0',
  `level` INT(5) NOT NULL DEFAULT '0',
  `name` VARCHAR(40) NOT NULL DEFAULT '',
  `hp` INT(5) NOT NULL DEFAULT '0',
  `hpregen` INT(3) NOT NULL DEFAULT '5',
  `fish_type` INT(1) NOT NULL DEFAULT '0',
  `fish_group` INT(1) NOT NULL DEFAULT '0',
  `fish_guts` INT(4) NOT NULL DEFAULT '0',
  `guts_check_time` INT(4) NOT NULL DEFAULT '0',
  `wait_time` INT(5) NOT NULL DEFAULT '0',
  `combat_time` INT(5) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`, `level`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fishing_skill_trees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fishing_skill_trees` ;

CREATE TABLE IF NOT EXISTS `fishing_skill_trees` (
  `skill_id` INT(10) NOT NULL DEFAULT '0',
  `level` INT(10) NOT NULL DEFAULT '0',
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `sp` INT(10) NOT NULL DEFAULT '0',
  `min_level` INT(10) NOT NULL DEFAULT '0',
  `costid` INT(10) NOT NULL DEFAULT '0',
  `cost` INT(10) NOT NULL DEFAULT '0',
  `isfordwarf` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`skill_id`, `level`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `forums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forums` ;

CREATE TABLE IF NOT EXISTS `forums` (
  `forum_id` INT(8) NOT NULL DEFAULT '0',
  `forum_name` VARCHAR(255) NOT NULL DEFAULT '',
  `forum_parent` INT(8) NOT NULL DEFAULT '0',
  `forum_post` INT(8) NOT NULL DEFAULT '0',
  `forum_type` INT(8) NOT NULL DEFAULT '0',
  `forum_perm` INT(8) NOT NULL DEFAULT '0',
  `forum_owner_id` INT(8) NOT NULL DEFAULT '0',
  UNIQUE INDEX `forum_id` (`forum_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games` ;

CREATE TABLE IF NOT EXISTS `games` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `idnr` INT(11) NOT NULL DEFAULT '0',
  `number1` INT(11) NOT NULL DEFAULT '0',
  `number2` INT(11) NOT NULL DEFAULT '0',
  `prize` INT(11) NOT NULL DEFAULT '0',
  `newprize` INT(11) NOT NULL DEFAULT '0',
  `prize1` INT(11) NOT NULL DEFAULT '0',
  `prize2` INT(11) NOT NULL DEFAULT '0',
  `prize3` INT(11) NOT NULL DEFAULT '0',
  `enddate` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `finished` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`, `idnr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gameservers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gameservers` ;

CREATE TABLE IF NOT EXISTS `gameservers` (
  `server_id` INT(11) NOT NULL DEFAULT '0',
  `hexid` VARCHAR(50) NOT NULL DEFAULT '',
  `host` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`server_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `global_tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global_tasks` ;

CREATE TABLE IF NOT EXISTS `global_tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(50) NOT NULL DEFAULT '',
  `type` VARCHAR(50) NOT NULL DEFAULT '',
  `last_activation` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `param1` VARCHAR(100) NOT NULL DEFAULT '',
  `param2` VARCHAR(100) NOT NULL DEFAULT '',
  `param3` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `helper_buff_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helper_buff_list` ;

CREATE TABLE IF NOT EXISTS `helper_buff_list` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `skill_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(25) NOT NULL DEFAULT '',
  `skill_level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `lower_level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `upper_level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `is_magic_class` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `henna_trees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `henna_trees` ;

CREATE TABLE IF NOT EXISTS `henna_trees` (
  `class_id` DECIMAL(10,0) NOT NULL DEFAULT '0',
  `symbol_id` DECIMAL(10,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`class_id`, `symbol_id`),
  INDEX `fk_henna_trees_henna1_idx` (`symbol_id` ASC),
  CONSTRAINT `fk_henna_trees_char_templates1`
    FOREIGN KEY (`class_id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_henna_trees_henna1`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `henna` (`symbol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `heroes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `heroes` ;

CREATE TABLE IF NOT EXISTS `heroes` (
  `char_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `char_name` VARCHAR(45) NOT NULL DEFAULT '',
  `class_id` DECIMAL(3,0) NOT NULL DEFAULT '0',
  `count` DECIMAL(3,0) NOT NULL DEFAULT '0',
  `played` DECIMAL(1,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`),
  INDEX `fk_heroes_char_templates1_idx` (`class_id` ASC),
  CONSTRAINT `fk_heroes_characters1`
    FOREIGN KEY (`char_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_heroes_char_templates1`
    FOREIGN KEY (`class_id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `items` ;

CREATE TABLE IF NOT EXISTS `items` (
  `owner_id` INT(11) NULL DEFAULT NULL,
  `object_id` INT(11) NOT NULL DEFAULT '0',
  `item_id` INT(11) NULL DEFAULT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `enchant_level` INT(11) NULL DEFAULT NULL,
  `loc` VARCHAR(10) NULL DEFAULT NULL,
  `loc_data` INT(11) NULL DEFAULT NULL,
  `price_sell` INT(11) NULL DEFAULT NULL,
  `price_buy` INT(11) NULL DEFAULT NULL,
  `time_of_use` INT(11) NULL DEFAULT NULL,
  `custom_type1` INT(11) NULL DEFAULT '0',
  `custom_type2` INT(11) NULL DEFAULT '0',
  `mana_left` DECIMAL(3,0) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`object_id`),
  INDEX `key_owner_id` (`owner_id` ASC),
  INDEX `key_loc` (`loc` ASC),
  INDEX `key_item_id` (`item_id` ASC),
  INDEX `key_time_of_use` (`time_of_use` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `itemsonground`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `itemsonground` ;

CREATE TABLE IF NOT EXISTS `itemsonground` (
  `object_id` INT(11) NOT NULL DEFAULT '0',
  `item_id` INT(11) NULL DEFAULT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `enchant_level` INT(11) NULL DEFAULT NULL,
  `x` INT(11) NULL DEFAULT NULL,
  `y` INT(11) NULL DEFAULT NULL,
  `z` INT(11) NULL DEFAULT NULL,
  `drop_time` DECIMAL(20,0) NULL DEFAULT NULL,
  `equipable` INT(1) NULL DEFAULT '0',
  PRIMARY KEY (`object_id`),
  CONSTRAINT `fk_itemsonground_items1`
    FOREIGN KEY (`object_id`)
    REFERENCES `items` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locations` ;

CREATE TABLE IF NOT EXISTS `locations` (
  `loc_id` INT(9) NOT NULL DEFAULT '0',
  `loc_x` INT(9) NOT NULL DEFAULT '0',
  `loc_y` INT(9) NOT NULL DEFAULT '0',
  `loc_zmin` INT(9) NOT NULL DEFAULT '0',
  `loc_zmax` INT(9) NOT NULL DEFAULT '0',
  `proc` INT(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`loc_id`, `loc_x`, `loc_y`),
  INDEX `proc` (`proc` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lvlupgain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lvlupgain` ;

CREATE TABLE IF NOT EXISTS `lvlupgain` (
  `classid` INT(3) NOT NULL DEFAULT '0',
  `defaulthpbase` DECIMAL(5,1) NOT NULL DEFAULT '0.0',
  `defaulthpadd` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `defaulthpmod` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `defaultcpbase` DECIMAL(5,1) NOT NULL DEFAULT '0.0',
  `defaultcpadd` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `defaultcpmod` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `defaultmpbase` DECIMAL(5,1) NOT NULL DEFAULT '0.0',
  `defaultmpadd` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `defaultmpmod` DECIMAL(4,2) NOT NULL DEFAULT '0.00',
  `class_lvl` INT(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`classid`),
  CONSTRAINT `fk_lvlupgain_char_templates1`
    FOREIGN KEY (`classid`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mapregion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mapregion` ;

CREATE TABLE IF NOT EXISTS `mapregion` (
  `region` INT(11) NOT NULL DEFAULT '0',
  `sec0` INT(2) NOT NULL DEFAULT '0',
  `sec1` INT(2) NOT NULL DEFAULT '0',
  `sec2` INT(2) NOT NULL DEFAULT '0',
  `sec3` INT(2) NOT NULL DEFAULT '0',
  `sec4` INT(2) NOT NULL DEFAULT '0',
  `sec5` INT(2) NOT NULL DEFAULT '0',
  `sec6` INT(2) NOT NULL DEFAULT '0',
  `sec7` INT(2) NOT NULL DEFAULT '0',
  `sec8` INT(2) NOT NULL DEFAULT '0',
  `sec9` INT(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`region`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `merchant_areas_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merchant_areas_list` ;

CREATE TABLE IF NOT EXISTS `merchant_areas_list` (
  `merchant_area_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `merchant_area_name` VARCHAR(25) NOT NULL DEFAULT '',
  `tax` DOUBLE(3,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `Chaotic` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`merchant_area_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `merchants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merchants` ;

CREATE TABLE IF NOT EXISTS `merchants` (
  `npc_id` INT(11) NOT NULL DEFAULT '0',
  `merchant_area_id` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`npc_id`),
  INDEX `fk_merchants_merchant_areas_list1_idx` (`merchant_area_id` ASC),
  CONSTRAINT `fk_merchants_npc1`
    FOREIGN KEY (`npc_id`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_merchants_merchant_areas_list1`
    FOREIGN KEY (`merchant_area_id`)
    REFERENCES `merchant_areas_list` (`merchant_area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `merchant_shopids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merchant_shopids` ;

CREATE TABLE IF NOT EXISTS `merchant_shopids` (
  `shop_id` DECIMAL(9,0) NOT NULL DEFAULT '0',
  `npc_id` VARCHAR(9) NULL DEFAULT NULL,
  PRIMARY KEY (`shop_id`),
  INDEX `fk_merchant_shopids_merchants1_idx` (`npc_id` ASC),
  CONSTRAINT `fk_merchant_shopids_merchants1`
    FOREIGN KEY (`npc_id`)
    REFERENCES `merchants` (`npc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `merchant_buylists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merchant_buylists` ;

CREATE TABLE IF NOT EXISTS `merchant_buylists` (
  `item_id` DECIMAL(9,0) NOT NULL DEFAULT '0',
  `price` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `shop_id` DECIMAL(9,0) NOT NULL DEFAULT '0',
  `order` DECIMAL(4,0) NOT NULL DEFAULT '0',
  `count` INT(11) NOT NULL DEFAULT '-1',
  `currentCount` INT(11) NOT NULL DEFAULT '-1',
  `time` INT(11) NOT NULL DEFAULT '0',
  `savetimer` DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`shop_id`, `order`),
  CONSTRAINT `fk_merchant_buylists_merchant_shopids1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `merchant_shopids` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `merchant_lease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merchant_lease` ;

CREATE TABLE IF NOT EXISTS `merchant_lease` (
  `merchant_id` INT(11) NOT NULL DEFAULT '0',
  `player_id` INT(11) NOT NULL DEFAULT '0',
  `bid` INT(11) NULL DEFAULT NULL,
  `type` INT(11) NOT NULL DEFAULT '0',
  `player_name` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`merchant_id`, `player_id`, `type`),
  INDEX `fk_merchant_lease_characters1_idx` (`player_id` ASC),
  CONSTRAINT `fk_merchant_lease_characters1`
    FOREIGN KEY (`player_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_merchant_lease_merchants1`
    FOREIGN KEY (`merchant_id`)
    REFERENCES `merchants` (`npc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `minions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minions` ;

CREATE TABLE IF NOT EXISTS `minions` (
  `boss_id` INT(11) NOT NULL DEFAULT '0',
  `minion_id` INT(11) NOT NULL DEFAULT '0',
  `amount_min` INT(4) NOT NULL DEFAULT '0',
  `amount_max` INT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`boss_id`, `minion_id`),
  INDEX `fk_minions_npc2_idx` (`minion_id` ASC),
  CONSTRAINT `fk_minions_npc1`
    FOREIGN KEY (`boss_id`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_minions_npc2`
    FOREIGN KEY (`minion_id`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mods_wedding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mods_wedding` ;

CREATE TABLE IF NOT EXISTS `mods_wedding` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `player1Id` INT(11) NOT NULL DEFAULT '0',
  `player2Id` INT(11) NOT NULL DEFAULT '0',
  `married` VARCHAR(5) NULL DEFAULT NULL,
  `affianceDate` DECIMAL(20,0) NULL DEFAULT '0',
  `weddingDate` DECIMAL(20,0) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_mods_wedding_characters1_idx` (`player1Id` ASC),
  INDEX `fk_mods_wedding_characters2_idx` (`player2Id` ASC),
  CONSTRAINT `fk_mods_wedding_characters1`
    FOREIGN KEY (`player1Id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mods_wedding_characters2`
    FOREIGN KEY (`player2Id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `npcskills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `npcskills` ;

CREATE TABLE IF NOT EXISTS `npcskills` (
  `npcid` INT(11) NOT NULL DEFAULT '0',
  `skillid` INT(11) NOT NULL DEFAULT '0',
  `level` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`npcid`, `skillid`, `level`),
  CONSTRAINT `fk_npcskills_npc1`
    FOREIGN KEY (`npcid`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `olympiad_nobles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olympiad_nobles` ;

CREATE TABLE IF NOT EXISTS `olympiad_nobles` (
  `char_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `class_id` DECIMAL(3,0) NOT NULL DEFAULT '0',
  `char_name` VARCHAR(45) NOT NULL DEFAULT '',
  `olympiad_points` DECIMAL(10,0) NOT NULL DEFAULT '0',
  `competitions_done` DECIMAL(3,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_id`),
  INDEX `fk_olympiad_nobles_char_templates1_idx` (`class_id` ASC),
  CONSTRAINT `fk_olympiad_nobles_characters1`
    FOREIGN KEY (`char_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_olympiad_nobles_char_templates1`
    FOREIGN KEY (`class_id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pets` ;

CREATE TABLE IF NOT EXISTS `pets` (
  `item_obj_id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `name` VARCHAR(16) NULL DEFAULT NULL,
  `level` DECIMAL(11,0) NULL DEFAULT NULL,
  `curHp` DECIMAL(18,0) NULL DEFAULT NULL,
  `curMp` DECIMAL(18,0) NULL DEFAULT NULL,
  `exp` DECIMAL(20,0) NULL DEFAULT NULL,
  `sp` DECIMAL(11,0) NULL DEFAULT NULL,
  `karma` DECIMAL(11,0) NULL DEFAULT NULL,
  `pkkills` DECIMAL(11,0) NULL DEFAULT NULL,
  `fed` DECIMAL(11,0) NULL DEFAULT NULL,
  PRIMARY KEY (`item_obj_id`),
  CONSTRAINT `fk_pets_items1`
    FOREIGN KEY (`item_obj_id`)
    REFERENCES `items` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pets_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pets_stats` ;

CREATE TABLE IF NOT EXISTS `pets_stats` (
  `type` VARCHAR(25) NOT NULL DEFAULT '',
  `typeID` INT(5) NOT NULL DEFAULT '0',
  `level` INT(11) NOT NULL DEFAULT '0',
  `expMax` INT(20) NOT NULL DEFAULT '0',
  `hpMax` INT(11) NOT NULL DEFAULT '0',
  `mpMax` INT(11) NOT NULL DEFAULT '0',
  `patk` INT(11) NOT NULL DEFAULT '0',
  `pdef` INT(11) NOT NULL DEFAULT '0',
  `matk` INT(11) NOT NULL DEFAULT '0',
  `mdef` INT(11) NOT NULL DEFAULT '0',
  `acc` INT(11) NOT NULL DEFAULT '0',
  `evasion` INT(11) NOT NULL DEFAULT '0',
  `crit` INT(11) NOT NULL DEFAULT '0',
  `speed` INT(11) NOT NULL DEFAULT '0',
  `atk_speed` INT(11) NOT NULL DEFAULT '0',
  `cast_speed` INT(11) NOT NULL DEFAULT '0',
  `feedMax` INT(11) NOT NULL DEFAULT '0',
  `feedbattle` INT(11) NOT NULL DEFAULT '0',
  `feednormal` INT(11) NOT NULL DEFAULT '0',
  `loadMax` INT(11) NOT NULL DEFAULT '0',
  `hpregen` INT(11) NOT NULL DEFAULT '0',
  `mpregen` INT(11) NOT NULL DEFAULT '0',
  `owner_exp_taken` DECIMAL(3,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`typeID`, `level`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pledge_skill_trees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pledge_skill_trees` ;

CREATE TABLE IF NOT EXISTS `pledge_skill_trees` (
  `skill_id` INT(11) NULL DEFAULT NULL,
  `level` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(25) NULL DEFAULT NULL,
  `clan_lvl` INT(11) NULL DEFAULT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  `repCost` INT(11) NULL DEFAULT NULL,
  `itemId` INT(11) NULL DEFAULT NULL,
  INDEX `fk_pledge_skill_trees_etcitem1_idx` (`itemId` ASC),
  CONSTRAINT `fk_pledge_skill_trees_etcitem1`
    FOREIGN KEY (`itemId`)
    REFERENCES `etcitem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topic` ;

CREATE TABLE IF NOT EXISTS `topic` (
  `topic_id` INT(8) NOT NULL DEFAULT '0',
  `topic_forum_id` INT(8) NOT NULL DEFAULT '0',
  `topic_name` VARCHAR(255) NOT NULL DEFAULT '',
  `topic_date` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `topic_ownername` VARCHAR(255) NOT NULL DEFAULT '0',
  `topic_ownerid` INT(8) NOT NULL DEFAULT '0',
  `topic_type` INT(8) NOT NULL DEFAULT '0',
  `topic_reply` INT(8) NOT NULL DEFAULT '0',
  INDEX `fk_topic_forums1_idx` (`topic_forum_id` ASC),
  CONSTRAINT `fk_topic_forums1`
    FOREIGN KEY (`topic_forum_id`)
    REFERENCES `forums` (`forum_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posts` ;

CREATE TABLE IF NOT EXISTS `posts` (
  `post_id` INT(8) NOT NULL DEFAULT '0',
  `post_owner_name` VARCHAR(255) NOT NULL DEFAULT '',
  `post_ownerid` INT(8) NOT NULL DEFAULT '0',
  `post_date` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `post_topic_id` INT(8) NOT NULL DEFAULT '0',
  `post_forum_id` INT(8) NOT NULL DEFAULT '0',
  `post_txt` TEXT NOT NULL,
  INDEX `fk_posts_forums1_idx` (`post_forum_id` ASC),
  INDEX `fk_posts_topic1_idx` (`post_topic_id` ASC),
  CONSTRAINT `fk_posts_forums1`
    FOREIGN KEY (`post_forum_id`)
    REFERENCES `forums` (`forum_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_topic1`
    FOREIGN KEY (`post_topic_id`)
    REFERENCES `topic` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `quest_global_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quest_global_data` ;

CREATE TABLE IF NOT EXISTS `quest_global_data` (
  `quest_name` VARCHAR(40) NOT NULL DEFAULT '',
  `var` VARCHAR(20) NOT NULL DEFAULT '',
  `value` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`quest_name`, `var`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `raidboss_spawnlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `raidboss_spawnlist` ;

CREATE TABLE IF NOT EXISTS `raidboss_spawnlist` (
  `boss_id` INT(11) NOT NULL DEFAULT '0',
  `amount` INT(11) NOT NULL DEFAULT '0',
  `loc_x` INT(11) NOT NULL DEFAULT '0',
  `loc_y` INT(11) NOT NULL DEFAULT '0',
  `loc_z` INT(11) NOT NULL DEFAULT '0',
  `heading` INT(11) NOT NULL DEFAULT '0',
  `respawn_min_delay` INT(11) NOT NULL DEFAULT '43200',
  `respawn_max_delay` INT(11) NOT NULL DEFAULT '129600',
  `respawn_time` BIGINT(20) NOT NULL DEFAULT '0',
  `currentHp` DECIMAL(8,0) NULL DEFAULT NULL,
  `currentMp` DECIMAL(8,0) NULL DEFAULT NULL,
  PRIMARY KEY (`boss_id`, `loc_x`, `loc_y`, `loc_z`),
  CONSTRAINT `fk_raidboss_spawnlist_npc1`
    FOREIGN KEY (`boss_id`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `random_spawn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `random_spawn` ;

CREATE TABLE IF NOT EXISTS `random_spawn` (
  `groupId` INT(11) NOT NULL DEFAULT '0',
  `npcId` INT(11) NOT NULL DEFAULT '0',
  `count` INT(11) NOT NULL DEFAULT '0',
  `initialDelay` BIGINT(20) NOT NULL DEFAULT '-1',
  `respawnDelay` BIGINT(20) NOT NULL DEFAULT '-1',
  `despawnDelay` BIGINT(20) NOT NULL DEFAULT '-1',
  `broadcastSpawn` VARCHAR(5) NOT NULL DEFAULT 'false',
  `randomSpawn` VARCHAR(5) NOT NULL DEFAULT 'true',
  PRIMARY KEY (`groupId`),
  INDEX `fk_random_spawn_npc1_idx` (`npcId` ASC),
  CONSTRAINT `fk_random_spawn_npc1`
    FOREIGN KEY (`npcId`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `random_spawn_loc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `random_spawn_loc` ;

CREATE TABLE IF NOT EXISTS `random_spawn_loc` (
  `groupId` INT(11) NOT NULL DEFAULT '0',
  `x` INT(11) NOT NULL DEFAULT '0',
  `y` INT(11) NOT NULL DEFAULT '0',
  `z` INT(11) NOT NULL DEFAULT '0',
  `heading` INT(11) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`groupId`, `x`, `y`, `z`, `heading`),
  CONSTRAINT `fk_random_spawn_loc_random_spawn1`
    FOREIGN KEY (`groupId`)
    REFERENCES `random_spawn` (`groupId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `seven_signs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seven_signs` ;

CREATE TABLE IF NOT EXISTS `seven_signs` (
  `char_obj_id` INT(11) NOT NULL DEFAULT '0',
  `cabal` VARCHAR(4) NOT NULL DEFAULT '',
  `seal` INT(1) NOT NULL DEFAULT '0',
  `red_stones` INT(11) NOT NULL DEFAULT '0',
  `green_stones` INT(11) NOT NULL DEFAULT '0',
  `blue_stones` INT(11) NOT NULL DEFAULT '0',
  `ancient_adena_amount` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `contribution_score` DECIMAL(20,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`char_obj_id`),
  CONSTRAINT `fk_seven_signs_characters1`
    FOREIGN KEY (`char_obj_id`)
    REFERENCES `characters` (`obj_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `seven_signs_festival`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seven_signs_festival` ;

CREATE TABLE IF NOT EXISTS `seven_signs_festival` (
  `festivalId` INT(1) NOT NULL DEFAULT '0',
  `cabal` VARCHAR(4) NOT NULL DEFAULT '',
  `cycle` INT(4) NOT NULL DEFAULT '0',
  `date` BIGINT(50) NULL DEFAULT '0',
  `score` INT(5) NOT NULL DEFAULT '0',
  `members` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`festivalId`, `cabal`, `cycle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `seven_signs_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seven_signs_status` ;

CREATE TABLE IF NOT EXISTS `seven_signs_status` (
  `id` INT(3) NOT NULL DEFAULT '0',
  `current_cycle` INT(10) NOT NULL DEFAULT '1',
  `festival_cycle` INT(10) NOT NULL DEFAULT '1',
  `active_period` INT(10) NOT NULL DEFAULT '1',
  `date` INT(10) NOT NULL DEFAULT '1',
  `previous_winner` INT(10) NOT NULL DEFAULT '0',
  `dawn_stone_score` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `dawn_festival_score` INT(10) NOT NULL DEFAULT '0',
  `dusk_stone_score` DECIMAL(20,0) NOT NULL DEFAULT '0',
  `dusk_festival_score` INT(10) NOT NULL DEFAULT '0',
  `avarice_owner` INT(10) NOT NULL DEFAULT '0',
  `gnosis_owner` INT(10) NOT NULL DEFAULT '0',
  `strife_owner` INT(10) NOT NULL DEFAULT '0',
  `avarice_dawn_score` INT(10) NOT NULL DEFAULT '0',
  `gnosis_dawn_score` INT(10) NOT NULL DEFAULT '0',
  `strife_dawn_score` INT(10) NOT NULL DEFAULT '0',
  `avarice_dusk_score` INT(10) NOT NULL DEFAULT '0',
  `gnosis_dusk_score` INT(10) NOT NULL DEFAULT '0',
  `strife_dusk_score` INT(10) NOT NULL DEFAULT '0',
  `accumulated_bonus0` INT(10) NOT NULL DEFAULT '0',
  `accumulated_bonus1` INT(10) NOT NULL DEFAULT '0',
  `accumulated_bonus2` INT(10) NOT NULL DEFAULT '0',
  `accumulated_bonus3` INT(10) NOT NULL DEFAULT '0',
  `accumulated_bonus4` INT(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `siege_clans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siege_clans` ;

CREATE TABLE IF NOT EXISTS `siege_clans` (
  `castle_id` INT(1) NOT NULL DEFAULT '0',
  `clan_id` INT(11) NOT NULL DEFAULT '0',
  `type` INT(1) NULL DEFAULT NULL,
  `castle_owner` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`clan_id`, `castle_id`),
  INDEX `fk_siege_clans_castle1_idx` (`castle_id` ASC),
  CONSTRAINT `fk_siege_clans_castle1`
    FOREIGN KEY (`castle_id`)
    REFERENCES `castle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_siege_clans_clan_data1`
    FOREIGN KEY (`clan_id`)
    REFERENCES `clan_data` (`clan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_learn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skill_learn` ;

CREATE TABLE IF NOT EXISTS `skill_learn` (
  `npc_id` INT(11) NOT NULL DEFAULT '0',
  `class_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`npc_id`, `class_id`),
  INDEX `fk_skill_learn_char_templates1_idx` (`class_id` ASC),
  CONSTRAINT `fk_skill_learn_npc1`
    FOREIGN KEY (`npc_id`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_learn_char_templates1`
    FOREIGN KEY (`class_id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_spellbooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skill_spellbooks` ;

CREATE TABLE IF NOT EXISTS `skill_spellbooks` (
  `skill_id` INT(11) NOT NULL DEFAULT '-1',
  `item_id` INT(11) NOT NULL DEFAULT '-1',
  INDEX `skill_id` (`skill_id` ASC, `item_id` ASC),
  INDEX `fk_skill_spellbooks_etcitem1_idx` (`item_id` ASC),
  CONSTRAINT `fk_skill_spellbooks_etcitem1`
    FOREIGN KEY (`item_id`)
    REFERENCES `etcitem` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `skill_trees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `skill_trees` ;

CREATE TABLE IF NOT EXISTS `skill_trees` (
  `class_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `skill_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(40) NOT NULL DEFAULT '',
  `sp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `min_level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`class_id`, `skill_id`, `level`),
  CONSTRAINT `fk_skill_trees_char_templates1`
    FOREIGN KEY (`class_id`)
    REFERENCES `char_templates` (`ClassId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `spawnlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spawnlist` ;

CREATE TABLE IF NOT EXISTS `spawnlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(40) NOT NULL DEFAULT '',
  `count` INT(9) NOT NULL DEFAULT '0',
  `npc_templateid` INT(9) NOT NULL DEFAULT '0',
  `locx` INT(9) NOT NULL DEFAULT '0',
  `locy` INT(9) NOT NULL DEFAULT '0',
  `locz` INT(9) NOT NULL DEFAULT '0',
  `randomx` INT(9) NOT NULL DEFAULT '0',
  `randomy` INT(9) NOT NULL DEFAULT '0',
  `heading` INT(9) NOT NULL DEFAULT '0',
  `respawn_delay` INT(9) NOT NULL DEFAULT '0',
  `loc_id` INT(9) NOT NULL DEFAULT '0',
  `periodOfDay` DECIMAL(2,0) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `key_npc_templateid` (`npc_templateid` ASC),
  CONSTRAINT `fk_spawnlist_npc1`
    FOREIGN KEY (`npc_templateid`)
    REFERENCES `npc` (`idTemplate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 76235
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `teleport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teleport` ;

CREATE TABLE IF NOT EXISTS `teleport` (
  `Description` VARCHAR(75) NULL DEFAULT NULL,
  `id` DECIMAL(11,0) NOT NULL DEFAULT '0',
  `loc_x` DECIMAL(9,0) NULL DEFAULT NULL,
  `loc_y` DECIMAL(9,0) NULL DEFAULT NULL,
  `loc_z` DECIMAL(9,0) NULL DEFAULT NULL,
  `price` DECIMAL(6,0) NULL DEFAULT NULL,
  `fornoble` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `walker_routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `walker_routes` ;

CREATE TABLE IF NOT EXISTS `walker_routes` (
  `route_id` INT(11) NOT NULL DEFAULT '0',
  `npc_id` INT(11) NOT NULL DEFAULT '0',
  `move_point` INT(9) NOT NULL,
  `chatText` VARCHAR(255) NULL DEFAULT NULL,
  `move_x` INT(9) NOT NULL DEFAULT '0',
  `move_y` INT(9) NOT NULL DEFAULT '0',
  `move_z` INT(9) NOT NULL DEFAULT '0',
  `delay` INT(9) NOT NULL DEFAULT '0',
  `running` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`route_id`, `npc_id`, `move_point`),
  INDEX `fk_walker_routes_npc1_idx` (`npc_id` ASC),
  CONSTRAINT `fk_walker_routes_npc1`
    FOREIGN KEY (`npc_id`)
    REFERENCES `npc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zone` ;

CREATE TABLE IF NOT EXISTS `zone` (
  `id` INT(11) NOT NULL DEFAULT '0',
  `type` VARCHAR(25) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `x1` INT(11) NOT NULL DEFAULT '0',
  `y1` INT(11) NOT NULL DEFAULT '0',
  `x2` INT(11) NOT NULL DEFAULT '0',
  `y2` INT(11) NOT NULL DEFAULT '0',
  `z` INT(11) NOT NULL DEFAULT '0',
  `z2` INT(11) NOT NULL DEFAULT '0',
  `taxById` INT(11) NOT NULL DEFAULT '0')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zone_vertices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zone_vertices` ;

CREATE TABLE IF NOT EXISTS `zone_vertices` (
  `id` INT(11) NOT NULL,
  `order` INT(11) NOT NULL,
  `x` INT(11) NOT NULL,
  `y` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `order`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
